FROM node:10.16.3

RUN mkdir -p /srv/app/client
WORKDIR /srv/app/client

COPY package.json /srv/app/client
COPY package-lock.json /srv/app/client

RUN npm install 

COPY . /srv/app/client

CMD ['ng', 'serve', 'port', '4200']